# Generated by Django 3.2.4 on 2021-07-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_refferal_coupen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='refferal_coupen',
            new_name='RefferalCoupen',
        ),
    ]
