# Generated by Django 3.2.4 on 2021-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_refferal_coupen_refferalcoupen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferalcoupen',
            name='ref_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
