# Generated by Django 3.2.4 on 2021-07-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
