# Generated by Django 3.2.4 on 2021-06-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_images1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images1',
            field=models.ImageField(upload_to='productimages/'),
        ),
    ]
