# Generated by Django 3.2.4 on 2021-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
    ]
