# Generated by Django 3.2.4 on 2021-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210714_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
        migrations.AddField(
            model_name='product',
            name='category_offer_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer_price',
            field=models.FloatField(null=True),
        ),
    ]
