# Generated by Django 3.2.4 on 2021-07-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_coupon_reviewrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coupon',
            new_name='Coupon_add',
        ),
    ]
