# Generated by Django 3.2.4 on 2021-07-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_usedoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedoffer',
            name='is_orderd',
            field=models.BooleanField(default=False),
        ),
    ]
